<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>StarTrek</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\StarTrekWebGadgets\StarTrekWebGadgets.csproj" />
    </ItemGroup>

</Project>
